name: Update List

on: 
  workflow_dispatch:
  schedule:
    - cron: '35 * * * *'

defaults:
  run:
    working-directory: ./scripts

jobs:
  run:
    name: Update deadlist.txt and locklog.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
    
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Update List
        run: node update.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'periodically update'
          add: '*.txt'